# Training Pipeline

In [1]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [3]:
df.shape

(569, 33)

```Text
inplace = “Modify the original object directly instead of creating a new one.”

In [4]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)
df.head(n=5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

**Train Test Split**

In [5]:
X_train, X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

**Scaling**

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [7]:
X_train

array([[-0.35543721, -0.73708306, -0.3793862 , ..., -0.47110769,
         0.63675   , -0.2937122 ],
       [-0.14706964, -0.70025724, -0.19222714, ..., -0.42292126,
        -0.14319788, -0.32177867],
       [-0.89043505, -1.02248321, -0.89060013, ..., -0.72027424,
         0.48584359, -0.5889499 ],
       ...,
       [-1.12696041, -0.43557162, -1.12025818, ..., -1.20564579,
        -0.04471159, -0.30720569],
       [ 0.88632092,  0.84872905,  0.75746204, ..., -0.49443846,
        -0.70552283, -1.00562907],
       [ 1.47481853, -0.12715533,  1.45624367, ...,  1.39108439,
         0.58750686,  0.34048214]], shape=(455, 30))

**Label Encoding**

In [8]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

**Numpy arrays to Pytorch Tensors**

In [9]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [10]:
X_train_tensor.shape

torch.Size([455, 30])

In [11]:
y_train_tensor.shape

torch.Size([455])

**Defining the model**

In [12]:
class MySimpleNN():
    
    def __init__(self,X):

        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)


    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

        # calculate loss
        loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

**Important Parameters**

In [13]:
learning_rate=0.1
epochs=25

**Training Pipeline**

In [14]:
# create model

model=MySimpleNN(X_train_tensor)


# define loop

for epoch in range(epochs):
    
    
    # forward Pass
    y_pred=model.forward(X_train_tensor)


    # calculate loss
    loss=model.loss_function(y_pred,y_train_tensor)
    print(f"Epoch :{epoch+1},loss:{loss.item()}")

    # backward pass
    loss.backward()


# parameters update
    with torch.no_grad():
        model.weights-=learning_rate*model.weights.grad
        model.bias-=learning_rate*model.bias.grad

# Zero gradients

    model.weights.grad.zero_()
    model.bias.grad.zero_()


# print loss in each epoch
print(f"Epoch : {epoch+1},loss:{loss.item()}")

Epoch :1,loss:3.6120864839167717
Epoch :2,loss:3.4857674006051176
Epoch :3,loss:3.3536034309197835
Epoch :4,loss:3.2176883797722904
Epoch :5,loss:3.078791336481102
Epoch :6,loss:2.9373992386868024
Epoch :7,loss:2.7940942488765823
Epoch :8,loss:2.6506248853051444
Epoch :9,loss:2.499322725198752
Epoch :10,loss:2.344273582735709
Epoch :11,loss:2.190461457536524
Epoch :12,loss:2.0352788381428897
Epoch :13,loss:1.8782226696065123
Epoch :14,loss:1.722767057185133
Epoch :15,loss:1.5768476788292909
Epoch :16,loss:1.4403469340268815
Epoch :17,loss:1.3133479138657889
Epoch :18,loss:1.1992667678057756
Epoch :19,loss:1.1018176858787123
Epoch :20,loss:1.0213842896781562
Epoch :21,loss:0.9573266989684787
Epoch :22,loss:0.907970100610037
Epoch :23,loss:0.8708344758632489
Epoch :24,loss:0.843117689446523
Epoch :25,loss:0.8222456955222642
Epoch : 25,loss:0.8222456955222642

```TEXT
Gradients tell what is wrong.
Weight updates apply the correction.

In [15]:
model.bias

tensor([-0.0940], dtype=torch.float64, requires_grad=True)

In [16]:
# Evaluation
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.9).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f"accuracy: {accuracy.item()}")
print(y_pred)

accuracy: 0.6662049889564514
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

**Improved code**

- Using built in activation function
- Using built in loss function
- Using optimizers as well

In [19]:
import torch
import torch.nn as nn


class MySimpleNN(nn.Module):
    
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out 

    
learning_rate=0.1
epochs=25
loss_function=nn.BCELoss()




# create model

model=MySimpleNN(X_train_tensor.shape[1])
#optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)


# define loop

for epoch in range(epochs):
    
    
    # forward Pass
    y_pred=model(X_train_tensor)


    # calculate loss
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))
    print(f"Epoch :{epoch+1},loss:{loss.item()}")

    # backward pass
    loss.backward()


# parameters update
    optimizer.step()
# Zero gradients

    optimizer.zero_grad()

# print loss in each epoch
print(f"Epoch : {epoch+1},loss:{loss.item()}")

Epoch :1,loss:0.8236866593360901
Epoch :2,loss:0.5875511169433594
Epoch :3,loss:0.4660191237926483
Epoch :4,loss:0.3969051241874695
Epoch :5,loss:0.3525554835796356
Epoch :6,loss:0.3215036988258362
Epoch :7,loss:0.2983936369419098
Epoch :8,loss:0.2804102599620819
Epoch :9,loss:0.2659345865249634
Epoch :10,loss:0.25396960973739624
Epoch :11,loss:0.24386772513389587
Epoch :12,loss:0.23518969118595123
Epoch :13,loss:0.2276269793510437
Epoch :14,loss:0.22095635533332825
Epoch :15,loss:0.21501217782497406
Epoch :16,loss:0.20966875553131104
Epoch :17,loss:0.20482897758483887
Epoch :18,loss:0.20041635632514954
Epoch :19,loss:0.19637002050876617
Epoch :20,loss:0.19264063239097595
Epoch :21,loss:0.18918782472610474
Epoch :22,loss:0.18597817420959473
Epoch :23,loss:0.18298378586769104
Epoch :24,loss:0.180181086063385
Epoch :25,loss:0.1775500625371933
Epoch : 25,loss:0.1775500625371933